// This file is used by Code Analysis to maintain SuppressMessage
// attributes that are applied to this project.
// Project-level suppressions either have no target or are given
// a specific target and scoped to a namespace, type, member, etc.

using System.Diagnostics.CodeAnalysis;

[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericB`3")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericB`3")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericB`3")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericB`3")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGeneric`1")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericA`2")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IWrongBaseGeneric`1")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IWrongBaseGenericA`2")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGeneric`1")]
[assembly: SuppressMessage("Major Code Smell", "S2326:Unused type parameters should be removed", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGenericA`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericA`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericA`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericA2`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericA2`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericB`3")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericB`3")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGeneric2`1")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGeneric2`1")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA2`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA2`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA3`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA3`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA4`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ChildGenericA4`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericA`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IBaseGenericA`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IChildGeneric2`1")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IChildGeneric2`1")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IChildGenericA2`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IChildGenericA2`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IWrongBaseGenericA`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.IWrongBaseGenericA`2")]
[assembly: SuppressMessage("Naming", "CA1715:Identifiers should have correct prefix", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGenericA`2")]
[assembly: SuppressMessage("StyleCop.CSharp.NamingRules", "SA1314:Type parameter names should begin with T", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGenericA`2")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.BaseGenericB`3")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.Class1")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ClassA")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ClassB")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ClassB2")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.ClassC")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGeneric`1")]
[assembly: SuppressMessage("Minor Code Smell", "S2094:Classes should not be empty", Justification = "<Pending>", Scope = "type", Target = "~T:ZymLabs.NSwag.FluentValidation.Tests.WrongBaseGenericA`2")]
